<main id="presentation">
	<section>
		<h1>Présentation</h1>
		<article>
			<figure>
				<figcaption>Découvrez nos créations!</figcaption>
				<img src="img/slideMobile.jpg" alt="Bracelets" id="imagemin">

				<div id="slider">
					<img src="img/slider/cadre1.png" alt="Cadre de diaporama" id="cadre">
					<img src="img/slider/img4.jpg" alt="Bracelets" id="image">
				</div>
	            <div id="navigation">
	            	<i class="fa fa-arrow-up" id="arrow"></i>
	                <button id="previous" title="Image précédente" class = "cacher"><i class="fa fa-backward"></i></button>

	                <button id="toggle" title="Démarrer le carrousel" class = "cacher"><i class="fa fa-play"></i></button>

	                <button id="next" title="Image suivante" class = "cacher"><i class="fa fa-forward"></i></button>
	            </div>
			</figure>
		</article>
		<article id="activites">
			<h2>Activités <strong>artisanales et culturelles</strong></h2>
			<h3>Situé à Tarbes l'association Artisanat-Ménestrel <br /> regroupe plusieurs savoir faire :</h3>
				<ul>
					<li><strong>Créations originales en cuir</strong></li>
					<li><strong>Céramique traditionnelle et fantaisiste</strong></li>
					<li><strong>Tableaux dans le style d'avant-garde Russe</strong></li>
					<li><strong>Cours de Russe</strong></li>
				</ul>
		</article>
	</section>

	<aside>
		<h2>Stages et commandes</h2>

		<p>Chaque objet est fait-main et unique. Vous avez votre idée ? Vous voulez participer à sa création ? Contactez l'auteur pour en discuter et, pourquoi pas, faire une commande sur mesure avec des couleurs de votre choix. Vous pouvez aussi suivre un atelier et fabriquer vous-même votre objet.</p>

		<p>Association Ménestrel propose également des cours de Russe. (Voir la rubrique Cours de Russe).</p>
	</aside>
</main>
