<!DOCTYPE html>
<html lang="fr">

	<head>
		<title>Artisanat-Ménestrel : <?=$page_title; ?></title>
		<meta name="description" content="Artisanat-Ménestrel regroupe plusieurs savoir faire : créations en cuir, céramique, painture, cours de la langue russe." />
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta charset="utf-8">
		<link rel="icon" href="https://artisanat-menestrel.000webhostapp.com/img/chien2.jpg" type="image/jpg">
		<link rel="stylesheet" type="text/css" href="css/normalize.css">
		<link rel="stylesheet" type="text/css" href="css/font-awesome.min.css">
		<link rel="stylesheet" type="text/css" href="css/style.css">
	</head>

	<body>
	<div id="totale">
		<header>
			<div class="un">
				<div class ="deux">
					<div id="header" class ="conteineur">
						<img src="img/logomin.png" alt="Artisanat - Menestrel" id="logomin">
						<img src="img/logomax.png" alt="Artisanat - Menestrel" id="logomax">
						<img src="img/ornmt2.png" alt="Ornement abstrait">
					</div>
				</div>
			</div>
		</header>

			<?php include $template_name; ?>

		<footer id="footer">
			<div class="deux">
				<div class="conteineur">
					<h2>Contacts :</h2>
					<p>Pour nous contacter ou effectuer des commandes vous pouvez nous écrire sur : menestrel78280@gmail.com</p> 

					<p>Réalisation de site - A. Pagnoux : <a href="http://a.pagnoux.free.fr">a.pagnoux.free.fr</a></p>
					<a href="#header" class="retour"><i class="fa fa-chevron-up"></i></a>
				</div>
			</div>
		</footer>

		<nav id="nav">
			<a href="index.php"><img src="img/ornmt1.png" alt="Ornement fleur"></a>
			<ul>
				<?php foreach($chapitres as $key => $value): ?>
				
				<li><a href="page.php?page=<?=$value['titre']; ?>" title="<?=$value['contenu_chapitre']; ?>"><?=$value['chapitre']; ?></a></li>
				<?php endforeach; ?>
				
			</ul>
		</nav>

		<div id="redirrection">
				<ul>
					<li><a href="#header"><i class="fa fa-chevron-up" aria-hidden="true"></i></a></li>
					<li><a href="#nav"><i class="fa fa-bars"></i></a></li>
					<li><a href="#footer"><i class="fa fa-envelope-o"></i></a></li>
				</ul>
		</div>

		<?php if ($template_name==="index.phtml" ): ?>
		<script type="text/javascript" src="js/slider.js"></script>
		<script type="text/javascript" src="js/index.js"></script>
		<?php endif; ?>
	</div>
	</body>
</html>